// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxs6Gt4H1o1kIRyRCpTHzFQft7FT2eNso',
    appId: '1:364108525373:web:d8efcd41c8f558a9fa1f54',
    messagingSenderId: '364108525373',
    projectId: 'zoom-clone-app-3b047',
    authDomain: 'zoom-clone-app-3b047.firebaseapp.com',
    storageBucket: 'zoom-clone-app-3b047.appspot.com',
    measurementId: 'G-45ZWTD1Y7T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7qcT0vpBV9CFeJ7cNr686n0xPTIEwwxA',
    appId: '1:364108525373:android:4d44b2fa45024052fa1f54',
    messagingSenderId: '364108525373',
    projectId: 'zoom-clone-app-3b047',
    storageBucket: 'zoom-clone-app-3b047.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMwHuHYzdkxSvQkQTzS_hKEcgg5lqL_ok',
    appId: '1:364108525373:ios:085dbf675da3439efa1f54',
    messagingSenderId: '364108525373',
    projectId: 'zoom-clone-app-3b047',
    storageBucket: 'zoom-clone-app-3b047.appspot.com',
    iosBundleId: 'com.example.zoomCloneApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMwHuHYzdkxSvQkQTzS_hKEcgg5lqL_ok',
    appId: '1:364108525373:ios:b6a25af294ade7f0fa1f54',
    messagingSenderId: '364108525373',
    projectId: 'zoom-clone-app-3b047',
    storageBucket: 'zoom-clone-app-3b047.appspot.com',
    iosBundleId: 'com.example.zoomCloneApp.RunnerTests',
  );
}
